name: curv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.*
  - pip=20.*
  - ase=3.*
  - jupyter=1.*
  - matplotlib-base=3.*
  - nglview=2.*
  - numpy=1.18.*
  - pandas=1.*
  - pymatgen=2020.*
  - pip:
    - dash>=1.12.0
    - dash-bio>=0.4.8
    - pychemcurv