name: curv
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip>=20.*
  - ase>=3.*
  - jupyter>=1.*
  - matplotlib>=3.*
  - nglview>=2.*
  - numpy>=1.18.*
  - pandas>=1.*
  - pymatgen>=2021.3.5
  - pip:
    - dash>=1.12.0
    - dash-bio>=0.4.8
    - git+git://github.com/gVallverdu/pychemcurv.git